<?php
	if (isset($_SESSION["logged_is_user"])) {
	    if ($_SESSION["role"] === "AD") {
	        header("Location: http://comedor.undac.edu.pe:8094/asistencia");
	    } else if ($_SESSION["role"] === "RE"){
	    	header("Location: http://comedor.undac.edu.pe:8094/reporte1");
	    } else if ($_SESSION["role"] === "BU"){
	    	header("Location: http://comedor.undac.edu.pe:8094/reporte1");
	    } else{
	        header("Location: http://comedor.undac.edu.pe:8094/novedades");
	    }
	    exit();
	}
?>

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<title>Comedor Undac</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="shortcut icon" href="http://comedor.undac.edu.pe:8094/img/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="http://comedor.undac.edu.pe:8094/css/estilo.css">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
</head>
</head>
<body>
<div class="container">
	<div class="row" id="contenedor">
		<div class="col-md-2"></div>
		<div class="col-md-8 col-sm-12">
			<div class="d-flex align-items-center justify-content-center" style="height: 100vh;">
				<div class="row" id="formulario">
					<div class="col-md-6" style="margin: 0px; padding: 0px;">
						<div class="otra" >
							<img src="http://comedor.undac.edu.pe:8094/img/comedor.jpg" class="img-fluid imagencomedor">
						</div>
					</div>
					<div class="col-md-6 text-center justify-content-center align-self-center">
						<div class="col-md-10 offset-md-1 form-input text-center justify-content-center align-self-center" id="caja">
							<img src="http://comedor.undac.edu.pe:8094/img/usuario.png" class="imagenusuario" width="80" height="80" style="border-radius: 150px;">
							<h4 class="titulologin">COMEDOR UNIVERSITARIO</h4>
							<h5>Bienvenido</h5>
							<form id="login">
								<div class="form-group sele">
									<select class="form-control" id="gradoAcad"   name="role" type="select">
	                                        <option value="" disabled="true" selected="true">-- Seleccione Rol --</option>
	                                        <option value="AD">Administrativo</option>
	                                        <option value="AL">Alumno</option>
	                                        <option value="RE">Rectorado</option>
	                                        <option value="BU">Bienestar Universitario</option>
	                                        <option value="SP">Soporte</option>
	                                 </select>
	                                  <div class="invalid-feedback">
						                  Aún no selecciona el <strong>rol</strong>
						              </div>
								</div>
								<div class="form-group user">

									<input type="number" class="form-control " name="user" placeholder="Código de Matricula o DNI" autocomplete="username">
									 <div class="invalid-feedback">
						                 Aún no ingresa el <strong>codigo de matricula</strong>
						             </div>
								</div>
								<div class="form-group contra">

									<input type="password" class="form-control" name="password" placeholder="Contraseña" autocomplete="password">
									 <div class="invalid-feedback">
						                 Aún no ingresa la <strong>contraseña</strong>
						             </div>
								</div>
								<div class="col-12">
									<button type="submit" class="btn btn-success">Ingresar</button>
								</div>
								<div class="clearfix" style="margin-top:5px;">

								</div>
									
								<div class="messaje" role="alert">
									
											<!--El "usuario" y "contraseña" de los nuevos comensales es el código de estudiante.-->

											<a href="https://play.google.com/store/apps/details?id=com.undac.undaccomedor" > <img src="http://www.gstatic.com/android/market_images/web/favicon_v2.ico">Descargar <strong>UNDAC Comedor(actualizado 15/01/2020)</strong></a>
								</div>

							</form>
						</div>

					</div>


						<!--<p style="text-align:   center">En atención al documento <strong>OFICIO N°389-2019-D-OBU-VRAC-UNDAC</strong>,  se realizó la inclusión de 16 alumnos al comedor universitario, a quienes se les comunica que pueden acceder y realizar una reserva desde hoy jueves, 24/10/2019</p> 

						<p style="text-align: center;"> <strong>Nota:</strong> El "usuario" y "contraseña" de los nuevos comensales inscritos por primera vez es el código de estudiante.</p>
 -->				</div>
			</div>
		</div>
		<div class="col-md-2"></div>

	<?php include "modal/modalInstalarApp.php";?>
	</div>
</div>
<script src="http://comedor.undac.edu.pe:8094/calendar/lib/jquery.min.js"></script>
<script src="http://comedor.undac.edu.pe:8094/js/login/login.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="http://comedor.undac.edu.pe:8094/js/principal.js"></script>

</body>
</html>
